version: '3.3'
services:
   frontend:
    container_name: renudia-frontend
    image: renudiafront:dev
    ports:
      - "86:6000"
    environment:
      - PORT=${PORT}
      - API_URL=${API_URL}
      - SECRET_KEY=${SECRET_KEY}
    networks:
      - red

    restart: always

networks:
  red: