from .user_resource import UserResource
from .message_resource import MessageResource
from .nutritional_record_resource import NutritionalRecordResource
from .food_resource import FoodResource
from .nutritionist_diabetic_resource import NutritionistDiabeticResource
