version: '3.3'
services:
  mysql:
    container_name: mysql-server
    image:  mysql:8-debian
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3336:3306"
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ~/mysql/_data:/var/lib/mysql
    restart: always
    networks:
      - red

  backend:
    container_name: renudia-backend
    image: renudiaback:dev
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_NAME=${MYSQL_DATABASE}
      - DATABASE_PORT=3306
      - DATABASE_URL=mysql-server
      - DATABASE_USER=${MYSQL_USER}
      - DATABASE_PASSWORD=${MYSQL_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRES=${JWT_ACCESS_TOKEN_EXPIRES}
    networks:
      red:
        ipv4_address: 172.19.0.10
    restart: always

networks:
  red: