from .user_repository import UserRepository
from .message_repository import MessageRepository
from .nutritional_record_repository import NutritionalRecordRepository
from .food_repository import FoodRepository
from .inscription_repository import InscriptionRepository
from .token_disabled_repository import TokenDisabledRepository
from .doctor_repository import DoctorRepository
